// RFCat Web - native RFCat firmware protocol over WebUSB
const C={APP_SYSTEM:0xff,APP_NIC:0x42,SYS_PEEK:0x80,SYS_POKE:0x81,SYS_PING:0x82,SYS_RFMODE:0x88,SYS_PARTNUM:0x8e,NIC_RECV:0x01,NIC_XMIT:0x02,RF_RX:0x02,RF_TX:0x03,RF_IDLE:0x04};
const R={SYNC1:0xdf00,SYNC0:0xdf01,FREQ2:0xdf09,FSCAL2:0xdf1d,MDMCFG4:0xdf0c,MDMCFG3:0xdf0d,MDMCFG2:0xdf0e,FREND1:0xdf1a,TEST2:0xdf23,TEST1:0xdf24};
const SUPPORTED=[{vendorId:0x1d50,productId:0x6047},{vendorId:0x1d50,productId:0x6048},{vendorId:0x1d50,productId:0x605b},{vendorId:0x1d50,productId:0xecc1},{vendorId:0x0451,productId:0x4715}];
const $=id=>document.getElementById(id); const log=(s)=>{$('log').textContent+=`[${new Date().toLocaleTimeString()}] ${s}\n`;$('log').scrollTop=$('log').scrollHeight};
const u16=n=>new Uint8Array([n&255,(n>>8)&255]); const concat=(...xs)=>{let n=xs.reduce((a,x)=>a+x.length,0),o=new Uint8Array(n),p=0;for(const x of xs){o.set(x,p);p+=x.length}return o};
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,'0').toUpperCase()).join(' '); const text=b=>new TextDecoder().decode(b).replace(/\0/g,'');
class RFCatUSB extends EventTarget{
 constructor(){super();this.device=null;this.running=false;this.buf=new Uint8Array();this.waiters=[]}
 async connect(){if(!navigator.usb)throw new Error('WebUSB is unavailable. Use desktop Chrome/Edge over HTTPS or localhost.');this.device=await navigator.usb.requestDevice({filters:SUPPORTED});await this.device.open();if(!this.device.configuration)await this.device.selectConfiguration(1);await this.device.claimInterface(0);this.running=true;this.readLoop();await this.ping();}
 async disconnect(){this.running=false;try{await this.device?.releaseInterface(0)}catch{}try{await this.device?.close()}catch{}this.device=null}
 async readLoop(){while(this.running&&this.device?.opened){try{const r=await this.device.transferIn(5,512);if(r.status==='ok'&&r.data?.byteLength)this.feed(new Uint8Array(r.data.buffer,r.data.byteOffset,r.data.byteLength))}catch(e){if(this.running){log(`USB read: ${e.message}`);await new Promise(r=>setTimeout(r,100))}}}}
 feed(chunk){this.buf=concat(this.buf,chunk);for(;;){let at=this.buf.indexOf(0x40);if(at<0){this.buf=new Uint8Array();return}if(at>0)this.buf=this.buf.slice(at);if(this.buf.length<5)return;const app=this.buf[1],cmd=this.buf[2],len=this.buf[3]|(this.buf[4]<<8);if(this.buf.length<5+len)return;const payload=this.buf.slice(5,5+len);this.buf=this.buf.slice(5+len);const i=this.waiters.findIndex(w=>w.app===app&&w.cmd===cmd);if(i>=0){const w=this.waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(payload)}else if(app===C.APP_NIC&&cmd===C.NIC_RECV)this.dispatchEvent(new CustomEvent('packet',{detail:payload}));else this.dispatchEvent(new CustomEvent('frame',{detail:{app,cmd,payload}}));}}
 wait(app,cmd,ms=3000){return new Promise((resolve,reject)=>{const w={app,cmd,resolve};w.timer=setTimeout(()=>{this.waiters=this.waiters.filter(x=>x!==w);reject(new Error(`Timeout waiting for ${app.toString(16)}:${cmd.toString(16)}`))},ms);this.waiters.push(w)})}
 async send(app,cmd,payload=new Uint8Array(),timeout=3000){const frame=concat(new Uint8Array([app,cmd]),u16(payload.length),payload);const pending=this.wait(app,cmd,timeout);for(let p=0;p<frame.length;p+=64){const r=await this.device.transferOut(5,frame.slice(p,p+64));if(r.status!=='ok')throw new Error(`USB write ${r.status}`)}return pending}
 ping(){return this.send(C.APP_SYSTEM,C.SYS_PING,new TextEncoder().encode('RFCAT-WEB'))}
 peek(addr,count=1){return this.send(C.APP_SYSTEM,C.SYS_PEEK,concat(u16(count),u16(addr)))}
 poke(addr,data){return this.send(C.APP_SYSTEM,C.SYS_POKE,concat(u16(addr),data))}
 mode(m){return this.send(C.APP_SYSTEM,C.SYS_RFMODE,new Uint8Array([m]))}
 async setFrequency(hz){const num=Math.floor(hz*((0x10000/1e6)/24));const f=new Uint8Array([(num>>16)&255,(num>>8)&255,num&255]);let cal=0x2a;if((hz>615e6&&hz<848e6)||(hz>369e6&&hz<424e6)||hz<318e6)cal=0x0a;await this.mode(C.RF_IDLE);await this.poke(R.FREQ2,f);await this.poke(R.FSCAL2,new Uint8Array([cal]));}
 async setDataRate(rate){let e,m;for(e=0;e<16;e++){m=Math.round(rate*2**28/(2**e*24e6)-256);if(m<256)break}if(e===16||m<0)throw new Error('Unsupported data rate');let m4=(await this.peek(R.MDMCFG4))[0];m4=(m4&0xf0)|(e&0x0f);await this.poke(R.MDMCFG3,new Uint8Array([m]));await this.poke(R.MDMCFG4,new Uint8Array([m4]));}
 async setBandwidth(bw){let be,bm,actual;outer:for(be=0;be<4;be++)for(bm=0;bm<4;bm++){actual=24e6/(8*(4+bm)*2**be);if(actual<=bw){break outer}}let m4=(await this.peek(R.MDMCFG4))[0];m4=(m4&0x0f)|(be<<6)|(bm<<4);await this.poke(R.MDMCFG4,new Uint8Array([m4]));await this.poke(R.FREND1,new Uint8Array([actual>102e3?0xb6:0x56]));await this.poke(R.TEST2,new Uint8Array([actual>325e3?0x88:0x81]));await this.poke(R.TEST1,new Uint8Array([actual>325e3?0x31:0x35]));return actual;}
 async setModulation(mod){let v=(await this.peek(R.MDMCFG2))[0];v=(v&~0x70)|(mod&0x70);await this.poke(R.MDMCFG2,new Uint8Array([v]));}
 async setSync(word,mode){await this.poke(R.SYNC1,new Uint8Array([(word>>8)&255,word&255]));let v=(await this.peek(R.MDMCFG2))[0];v=(v&~7)|(mode&7);await this.poke(R.MDMCFG2,new Uint8Array([v]));}
 async config(){const b=await this.peek(0xdf00,0x3e);const num=(b[9]<<16)|(b[10]<<8)|b[11],freq=num/((0x10000/1e6)/24);const de=b[12]&15,dm=b[13],rate=24e6*(256+dm)*2**de/2**28;const be=(b[12]>>6)&3,bm=(b[12]>>4)&3,bw=24e6/(8*(4+bm)*2**be);return{raw:b,freq,rate,bw,mod:b[14]&0x70,sync:(b[0]<<8)|b[1],syncMode:b[14]&7,marc:b[0x3b]&0x1f}}
 transmit(data,repeat=0,offset=0){if(data.length>255)throw new Error('MVP TX payload limit is 255 bytes');return this.send(C.APP_NIC,C.NIC_XMIT,concat(u16(data.length),u16(repeat),u16(offset),data),10000)}
}
const d=new RFCatUSB();let listening=false,pc=0,bc=0;
function enabled(v){for(const id of ['apply','readcfg','idle','rx','listen','transmit'])$(id).disabled=!v} enabled(false);
function parseHex(s){const clean=s.replace(/0x/gi,'').replace(/[^0-9a-f]/gi,'');if(clean.length%2)throw new Error('Hex payload must contain complete bytes');return new Uint8Array(clean.match(/.{2}/g)?.map(x=>parseInt(x,16))||[])}
async function refresh(){const c=await d.config();$('freq').value=(c.freq/1e6).toFixed(6);$('drate').value=Math.round(c.rate);$('bw').value=(c.bw/1e3).toFixed(3);$('mod').value=String(c.mod);$('sync').value=c.sync.toString(16).padStart(4,'0').toUpperCase();$('syncmode').value=String(c.syncMode);$('configSummary').textContent=`${(c.freq/1e6).toFixed(6)} MHz · ${Math.round(c.rate)} baud · ${(c.bw/1e3).toFixed(1)} kHz BW · MARCSTATE 0x${c.marc.toString(16).padStart(2,'0')}`}
$('connect').onclick=async()=>{try{if(d.device){await d.disconnect();document.body.classList.remove('connected');$('status').textContent='Disconnected';$('connect').textContent='Connect YS1';enabled(false);return}await d.connect();document.body.classList.add('connected');$('status').textContent=`${d.device.productName||'RFCat'} connected`;$('connect').textContent='Disconnect';enabled(true);log(`Connected VID ${d.device.vendorId.toString(16)} PID ${d.device.productId.toString(16)}`);await refresh()}catch(e){log(`ERROR: ${e.message}`);alert(e.message)}};
$('readcfg').onclick=()=>refresh().catch(e=>log(`ERROR: ${e.message}`));$('idle').onclick=()=>d.mode(C.RF_IDLE).then(()=>log('Radio → IDLE')).catch(e=>log(e.message));$('rx').onclick=()=>d.mode(C.RF_RX).then(()=>log('Radio → RX')).catch(e=>log(e.message));
$('apply').onclick=async()=>{try{await d.mode(C.RF_IDLE);await d.setFrequency(Number($('freq').value)*1e6);await d.setDataRate(Number($('drate').value));await d.setBandwidth(Number($('bw').value)*1e3);await d.setModulation(Number($('mod').value));await d.setSync(parseInt($('sync').value,16),Number($('syncmode').value));await refresh();log('Radio configuration applied')}catch(e){log(`ERROR: ${e.message}`)}};
$('listen').onclick=async()=>{try{listening=!listening;$('listen').textContent=listening?'Stop listening':'Start listening';await d.mode(listening?C.RF_RX:C.RF_IDLE);log(listening?'Listening for RFCat RX packets':'Listening stopped')}catch(e){listening=false;log(`ERROR: ${e.message}`)}};
d.addEventListener('packet',e=>{if(!listening)return;const b=e.detail;pc++;bc+=b.length;$('packets').textContent=pc;$('bytes').textContent=bc;const empty=$('.empty');if(empty)empty.remove();const el=document.createElement('div');el.className='packet';el.innerHTML=`<div class="meta">${new Date().toLocaleTimeString()} · ${b.length} bytes</div><div class="hex"></div>`;el.querySelector('.hex').textContent=hex(b);$('packetList').prepend(el)});
$('transmit').onclick=async()=>{try{const b=parseHex($('payload').value);if(!b.length)throw new Error('Enter a hex payload');await d.transmit(b,Number($('repeat').value),Number($('offset').value));log(`TX ${b.length} bytes: ${hex(b)}`)}catch(e){log(`ERROR: ${e.message}`)}};
$('clear').onclick=()=>{$('packetList').innerHTML='<div class="empty">No packets captured.</div>';pc=bc=0;$('packets').textContent=$('bytes').textContent='0'};$('clearlog').onclick=()=>$('log').textContent='';
navigator.usb?.addEventListener('disconnect',e=>{if(e.device===d.device){d.running=false;d.device=null;document.body.classList.remove('connected');$('status').textContent='Disconnected';$('connect').textContent='Connect YS1';enabled(false);log('Device disconnected')}});
log(navigator.usb?'WebUSB ready. Connect a YARD Stick One.':'WebUSB unavailable in this browser.');
